name: Build

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World!
              uses: ./.github/actions/build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: hello-artifact
                path: hello.txt
