name: Build

on:
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Print Hello World!
              uses: ./.github/actions/build
              with:
                repo_key: ${{ vars.REPO_KEY }}
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: hello-artifact
                path: hello.txt
