name: Deploy

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: hello-artifact
            - name: Print hello world from artifact
              run: cat hello.txt
            - name: Print DEV_KEY from artifact
              run: cat dev.txt
            - name: Print ANOTHER_SECRET from artifact
              run: cat repo-secret.txt
            - name: Print SECRET_KEY from artifact
              run: cat dev-secret.txt