name: Hello World Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello, World!"
    - name: More steps
      run: echo "Running more steps"
    - name:  Wait for 30 seconds
      run: echo "Waiting for 30 seconds" && sleep 30
    - name: Run more steps after waiting
      run: echo "Running more steps after waiting"
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Print Deploy Hello World
      run: echo "Deploy Hello, World!"
