name: Hello World Workflow

on:
  push:
  workflow_dispatch:

jobs:
  env-values:
    runs-on: ubuntu-latest
    steps:
      - name: Read env variable
        run: echo ${{ env.REPO_KEY }}
  main-build:
    uses: ./.github/workflows/build.yml
  main-deploy:
    needs: main-build
    uses: ./.github/workflows/deploy.yml
