name: Hello World Workflow

on:
  push:
  workflow_dispatch:

jobs:
  env-values:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Read vars
        run: echo '${{ toJson(vars) }}'
      - name: Read secrets
        run: echo '${{ toJSON(secrets) }}'
  main-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  main-deploy:
    needs: main-build
    uses: ./.github/workflows/deploy.yml
